/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calc;

/**
 *
 * @author Sugeng
 */
public class calc extends javax.swing.JFrame {

    /**
     * Creates new form calc
     */
    private float convertNumber;
    private String op;

    public calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtangka = new javax.swing.JTextField();
        satu1 = new javax.swing.JToggleButton();
        dua2 = new javax.swing.JToggleButton();
        tiga3 = new javax.swing.JToggleButton();
        empat4 = new javax.swing.JToggleButton();
        lima5 = new javax.swing.JToggleButton();
        enam6 = new javax.swing.JToggleButton();
        tujuh7 = new javax.swing.JToggleButton();
        delapan8 = new javax.swing.JToggleButton();
        sembilan9 = new javax.swing.JToggleButton();
        kosong0 = new javax.swing.JToggleButton();
        titik = new javax.swing.JToggleButton();
        bagi = new javax.swing.JToggleButton();
        kali = new javax.swing.JToggleButton();
        kurang = new javax.swing.JToggleButton();
        tambah = new javax.swing.JToggleButton();
        samadengan = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtangka.setEditable(false);
        txtangka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtangkaActionPerformed(evt);
            }
        });

        satu1.setText("1");
        satu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satu1ActionPerformed(evt);
            }
        });

        dua2.setText("2");
        dua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dua2ActionPerformed(evt);
            }
        });

        tiga3.setText("3");
        tiga3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiga3ActionPerformed(evt);
            }
        });

        empat4.setText("4");
        empat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empat4ActionPerformed(evt);
            }
        });

        lima5.setText("5");
        lima5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lima5ActionPerformed(evt);
            }
        });

        enam6.setText("6");
        enam6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enam6ActionPerformed(evt);
            }
        });

        tujuh7.setText("7");
        tujuh7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuh7ActionPerformed(evt);
            }
        });

        delapan8.setText("8");
        delapan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapan8ActionPerformed(evt);
            }
        });

        sembilan9.setText("9");
        sembilan9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilan9ActionPerformed(evt);
            }
        });

        kosong0.setText("0");
        kosong0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kosong0ActionPerformed(evt);
            }
        });

        titik.setText(".");
        titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikActionPerformed(evt);
            }
        });

        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });

        kali.setText("*");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });

        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });

        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });

        jButton1.setText("C");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tujuh7)
                            .addComponent(empat4)
                            .addComponent(satu1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lima5)
                                    .addComponent(delapan8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enam6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kali))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sembilan9)
                                        .addGap(18, 18, 18)
                                        .addComponent(bagi)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dua2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tiga3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kurang))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtangka, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(samadengan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kosong0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titik, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tambah))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtangka, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tujuh7, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(delapan8, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(sembilan9, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(bagi, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enam6, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(lima5, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(empat4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(kali, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(satu1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tiga3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dua2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kosong0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titik, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(samadengan, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtangkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtangkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtangkaActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        // TODO add your handling code here:
        if (op.equals("tambah")) {
            txtangka.setText(Float.toString(convertNumber + Float.parseFloat(txtangka.getText())));
        } else if (op.equals("kurang")) {
            txtangka.setText(Float.toString(convertNumber - Float.parseFloat(txtangka.getText())));
        } else if (op.equals("bagi")) {
            txtangka.setText(Float.toString(convertNumber / Float.parseFloat(txtangka.getText())));
        } else if (op.equals("kali")) {
            txtangka.setText(Float.toString(convertNumber * Float.parseFloat(txtangka.getText())));
        }
    }//GEN-LAST:event_samadenganActionPerformed

    private void empat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empat4ActionPerformed
        // TODO add your handling code here:
        txtangka.setText(txtangka.getText() + "4");

    }//GEN-LAST:event_empat4ActionPerformed

    private void kosong0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kosong0ActionPerformed
        // TODO add your handling code here:
        txtangka.setText(txtangka.getText() + "0");
    }//GEN-LAST:event_kosong0ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtangka.setText("");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void tujuh7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuh7ActionPerformed
        // TODO add your handling code here:
        txtangka.setText(txtangka.getText() + "7");
    }//GEN-LAST:event_tujuh7ActionPerformed

    private void delapan8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapan8ActionPerformed
        // TODO add your handling code here:
        txtangka.setText(txtangka.getText() + "8");
    }//GEN-LAST:event_delapan8ActionPerformed

    private void sembilan9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilan9ActionPerformed
        // TODO add your handling code here:
        txtangka.setText(txtangka.getText() + "9");
    }//GEN-LAST:event_sembilan9ActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        convertNumber = Float.parseFloat(txtangka.getText());
        op = "bagi";
        txtangka.setText("");
    }//GEN-LAST:event_bagiActionPerformed

    private void lima5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lima5ActionPerformed
        // TODO add your handling code here:
        txtangka.setText(txtangka.getText() + "5");
    }//GEN-LAST:event_lima5ActionPerformed

    private void enam6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enam6ActionPerformed
        // TODO add your handling code here:
        txtangka.setText(txtangka.getText() + "6");
    }//GEN-LAST:event_enam6ActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        convertNumber = Float.parseFloat(txtangka.getText());
        op = "kali";
        txtangka.setText("");
    }//GEN-LAST:event_kaliActionPerformed

    private void satu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satu1ActionPerformed
        // TODO add your handling code here:
        txtangka.setText(txtangka.getText() + "1");
    }//GEN-LAST:event_satu1ActionPerformed

    private void dua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dua2ActionPerformed
        // TODO add your handling code here:
        txtangka.setText(txtangka.getText() + "2");
    }//GEN-LAST:event_dua2ActionPerformed

    private void tiga3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiga3ActionPerformed
        // TODO add your handling code here:
        txtangka.setText(txtangka.getText() + "3");
    }//GEN-LAST:event_tiga3ActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        convertNumber = Float.parseFloat(txtangka.getText());
        op = "kurang";
        txtangka.setText("");
    }//GEN-LAST:event_kurangActionPerformed

    private void titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikActionPerformed
        // TODO add your handling code here:
        txtangka.setText(txtangka.getText() + ".");
    }//GEN-LAST:event_titikActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        convertNumber = Float.parseFloat(txtangka.getText());
        op = "tambah";
        txtangka.setText("");
    }//GEN-LAST:event_tambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bagi;
    private javax.swing.JToggleButton delapan8;
    private javax.swing.JToggleButton dua2;
    private javax.swing.JToggleButton empat4;
    private javax.swing.JToggleButton enam6;
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton kali;
    private javax.swing.JToggleButton kosong0;
    private javax.swing.JToggleButton kurang;
    private javax.swing.JToggleButton lima5;
    private javax.swing.JToggleButton samadengan;
    private javax.swing.JToggleButton satu1;
    private javax.swing.JToggleButton sembilan9;
    private javax.swing.JToggleButton tambah;
    private javax.swing.JToggleButton tiga3;
    private javax.swing.JToggleButton titik;
    private javax.swing.JToggleButton tujuh7;
    private javax.swing.JTextField txtangka;
    // End of variables declaration//GEN-END:variables
}
